---
galaxy_info:
  author: Steve Fulmer
  description: Role datarobot_setup for stevefulme1.datarobot
  license: GPL-3.0-or-later
  min_ansible_version: '2.16'
  galaxy_tags:
    - datarobot
dependencies: []
