---
- name: Validate required variables
  ansible.builtin.assert:
    that: datarobot_setup_api_url is defined
    quiet: true

- name: Execute datarobot_setup
  ansible.builtin.debug:
    msg: "Role datarobot_setup for stevefulme1.datarobot"
