---
- name: Validate required variables
  ansible.builtin.assert:
    that: model_monitor_api_url is defined
    quiet: true

- name: Execute model_monitor
  ansible.builtin.debug:
    msg: "Role model_monitor for stevefulme1.datarobot"
